name: build plugin core release jar
on:
  push:
    branches:
      - main
jobs:
  build:
    name: ZrLog plugin core package ${{ matrix.os }} ${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        architecture: [ amd64 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache node modules admin
        uses: actions/cache@v3
        with:
          path: src/main/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('src/main/frontend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        run: |
          mkdir -p /tmp/download
          bash -e bin/build-info.sh
          bash -e ./mvnw -Pnative -Dagent exec:exec@java-agent -U 
          bash -e ./mvnw -Pnative package
          bash bin/upload-bin.sh ${{ secrets.SECRET_ID }} ${{ secrets.SECRET_KEY }} ${{ secrets.BUCKET }} /tmp/download plugin/core